version: '3'

services:

  reverse-proxy:
    image: cortesben/cent-node-nginx-vim:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80

  node-server:
    depends_on:
      - reverse-proxy
    image: businessinsider/cms-node:oneSPA
    ports:
      - 8881:80
