version: '3'

services:

  reverse-proxy:
    image: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    links:
      - node-server

  node-server:
    image: businessinsider/cms-node:oneSPA
